name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  RAYLIB_VERSION: 5.5.0-0

jobs:
  # Linux x86_64 builds
  build-linux-x64-x11:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build raylib (X11)
        run: |
          sudo apt update
          sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DUSE_WAYLAND=OFF -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-x86_64-x11
        run: |
          ./build-java.sh
          ./build-native.sh
          ./build-docs.sh

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-linux-x64-x11
          path: ./*.jar

  build-linux-x64-wayland:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build raylib (Wayland)
        run: |
          sudo apt update
          sudo apt install libasound2-dev mesa-common-dev libwayland-dev libxkbcommon-dev wayland-protocols libwayland-egl1-mesa libgl1-mesa-dev libglu1-mesa-dev
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DUSE_WAYLAND=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-x86_64-wayland
        run: |
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-linux-x64-wayland
          path: ./*.jar

  build-linux-x64-drm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build raylib (DRM)
        run: |
          sudo apt update
          sudo apt install libasound2-dev mesa-common-dev libdrm-dev libgbm-dev libegl1-mesa-dev libgl1-mesa-dev
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DPLATFORM=DRM -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-x86_64-drm
        run: |
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-linux-x64-drm
          path: ./*.jar

  # Linux ARM64 builds
  build-linux-arm64-x11:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Set up ARM64 cross-compilation
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo dpkg --add-architecture arm64
          sudo bash -c 'cat > /etc/apt/sources.list.d/arm64.list << EOF
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates universe
          EOF'
          sudo apt update
          sudo apt install libasound2-dev:arm64 libx11-dev:arm64 libxrandr-dev:arm64 libxi-dev:arm64 libgl1-mesa-dev:arm64 libglu1-mesa-dev:arm64

      - name: Build raylib (ARM64, X11)
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DUSE_WAYLAND=OFF -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ ..
          make -j$(nproc)
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-arm64-x11
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-linux-arm64-x11
          path: ./*.jar

  build-linux-arm64-wayland:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Set up ARM64 cross-compilation
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo dpkg --add-architecture arm64
          sudo bash -c 'cat > /etc/apt/sources.list.d/arm64.list << EOF
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates universe
          EOF'
          sudo apt update
          sudo apt install libasound2-dev:arm64 libwayland-dev:arm64 libxkbcommon-dev:arm64 wayland-protocols libgl1-mesa-dev:arm64

      - name: Build raylib (ARM64, Wayland)
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DUSE_WAYLAND=ON -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ ..
          make -j$(nproc)
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-arm64-wayland
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-linux-arm64-wayland
          path: ./*.jar

  build-linux-arm64-drm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Set up ARM64 cross-compilation
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo dpkg --add-architecture arm64
          sudo bash -c 'cat > /etc/apt/sources.list.d/arm64.list << EOF
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal universe
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates universe
          EOF'
          sudo apt update
          sudo apt install libasound2-dev:arm64 libdrm-dev:arm64 libgbm-dev:arm64 libegl1-mesa-dev:arm64 libgl1-mesa-dev:arm64

      - name: Build raylib (ARM64, DRM)
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DPLATFORM=DRM -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ ..
          make -j$(nproc)
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-arm64-drm
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-linux-arm64-drm
          path: ./*.jar

  # macOS builds (Universal binary with x86_64 and ARM64)
  build-mac-universal:
    runs-on: macos-12
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build raylib (Universal)
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j$(sysctl -n hw.ncpu)
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: macosx-universal
        run: |
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-macosx-universal
          path: ./*.jar

  # Windows x86_64 build
  build-windows-x64:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release -A x64 ..
          msbuild raylib.sln /target:raylib /property:Configuration=Release /property:Platform=x64
          copy raylib\Release\raylib.lib ..\..
          cd ..\..
        shell: cmd

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: windows-x86_64
        run: |
          build-windows.bat
        shell: cmd

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-windows-x64
          path: ./*.jar

  # Windows ARM64 build
  build-windows-arm64:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release -A ARM64 ..
          msbuild raylib.sln /target:raylib /property:Configuration=Release /property:Platform=ARM64
          copy raylib\Release\raylib.lib ..\..
          cd ..\..
        shell: cmd

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: windows-arm64
        run: |
          build-windows.bat
        shell: cmd

      - name: Upload jar
        uses: actions/upload-artifact@v3.2.1
        with:
          name: jar-windows-arm64
          path: ./*.jar

  # Combine all artifacts
  combine-artifacts:
    needs: [build-linux-x64-x11, build-linux-x64-wayland, build-linux-x64-drm, 
            build-linux-arm64-x11, build-linux-arm64-wayland, build-linux-arm64-drm,
            build-mac-universal, build-windows-x64, build-windows-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Display structure
        run: ls -R

      - name: Combine JARs
        run: |
          mkdir -p combined
          find . -name "*.jar" -exec cp {} combined/ \;

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v3.2.1
        with:
          name: all-platform-jars
          path: combined/*.jar
